# Generated by Django 2.0.9 on 2018-11-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('branch', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=196)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=27)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.Banks')),
            ],
        ),
    ]
